# cloudbuild.yaml
# Build -> Push -> Deploy to Cloud Run (gen2) with GCS model URIs

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _REGION: "us-central1"
  _REPO: "guardrails"                     # Artifact Registry repo name
  _SERVICE: "guardrails-api"              # Cloud Run service name
  _TAG: "v1"                              # image tag

steps:
  # Build
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "-t"
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${_TAG}"
      - "."

  # Push
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${_TAG}"

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run","deploy","${_SERVICE}",
        "--image","${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${_TAG}",
        "--region","${_REGION}",
        "--allow-unauthenticated",
        "--cpu","1",
        "--memory","2Gi",
        "--concurrency","4",
        "--timeout","600",
        "--execution-environment","gen2",
        "--set-env-vars",
        "PORT=8080,CLS_BUCKET_URI=gs://guardhealth/,CLS_DIR_NEW=gs://guardhealth/cls_distilroberta_aug_60k,META_AUG=gs://guardhealth/pipeline_meta_aug_60k.json"
        # If you store the Gemini key in Secret Manager, uncomment the next two lines:
        # ,"--set-secrets"
        # ,"GEMINI_API_KEY=gemini-api-key:latest"
      ]
images:
  - "${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO}/${_SERVICE}:${_TAG}"
